#!/bin/bash
echo 'Best School' > \\\*\\\\\'\"Best\ School\"\\\'\\\\\*\$\\\?\\\*\\\*\\\*\\\*\\\*\:\)
total 40
drwxr-xr-x 2 root root 221 Feb 18 04:16 .
drwxr-xr-x 6 root root 121 Feb 13 10:21 ..
-rwxr--r-- 1 root root  30 Feb 15 13:09 0-hello_world
-rwxr--r-- 1 root root  30 Feb 15 16:38 1-confused_smiley
-rwxr--r-- 1 root root  28 Feb 16 16:30 2-hellofile
-rwxr--r-- 1 root root  40 Feb 16 16:38 3-twofiles
-rwxr--r-- 1 root root  36 Feb 16 16:46 4-lastlines
-rwxr--r-- 1 root root  36 Feb 16 16:49 5-firstlines
-rwxr--r-- 1 root root  41 Feb 16 16:57 6-third_line
-rwxr--r-- 1 root root 100 Feb 18 04:12 7-file
-rw-r--r-- 1 root root  32 Feb 18 04:16 #8-cwd_state#
lrwxrwxrwx 1 root root  22 Feb 18 04:15 .#8-cwd_state -> root@6f6574151e96.2119
-rw-r--r-- 1 root root  25 Feb 13 10:27 README.md
